countries = ['Japan', 'India', 'Georgia', 'Brazil', 'Lithuania', 'Latvia', 'Croatia', 'Mexico', 'Hungary', 'Soviet Union',
     'Philippines', 'Argentina', 'Russia', 'Ecuador', 'Estonia', 'Ukraine', 'South Korea', 'Vietnam', 'Hong Kong',
     'Puerto Rico', 'El Salvador', 'Chile', 'Honduras', 'Malawi', 'Thailand', 'Turkey', 'Niue', 'Cuba', 'Serbia',
     'China', 'Senegal', 'South Africa', 'Taiwan', 'Uruguay', 'Bosnia and Herzegovina', 'Tunisia', 'Indonesia',
     'Bulgaria', 'Czechoslovakia', 'Slovakia', 'Falkland Islands', 'Mongolia', 'Uzbekistan', 'Sri Lanka', 'Bangladesh',
     'San Marino', 'Egypt', 'St. Vincent and the Grenadines', 'Grenada', 'Antigua and Barbuda', 'Kosovo', 'Iran',
     'Palestinian Territory', 'Libyan Arab Jamahiriya', 'Peru', 'Colombia', 'Malaysia', 'Tajikistan', 'Singapore',
     'Slovenia', 'Belarus', 'American Samoa', 'Azerbaijan', 'Nigeria', 'Burundi', 'Kazakhstan', 'Albania', 'Nepal',
     'Syrian Arab Republic', 'Venezuela', 'Liechtenstein', 'Palau', 'Dominican Republic', 'Armenia', 'Lebanon',
     'Montserrat', 'New Caledonia', 'Kenya', 'Mauritius', 'Yugoslavia', 'Zimbabwe', 'Namibia', 'Belize', 'Montenegro',
     'Jamaica', 'Ghana', 'Qatar', 'Morocco', 'Macedonia', 'Paraguay', 'Barbados', 'Cook Islands', 'Guatemala',
     'French Polynesia', 'Myanmar', 'Costa Rica', 'Bolivia', 'Angola', 'Guinea', 'Djibouti', 'Iraq', 'Ethiopia',
     'Pakistan', 'Moldova', 'Nicaragua', 'United States Minor Outlying Islands', 'Trinidad and Tobago', 'Eritrea',
     'Mozambique', 'Zambia', 'Cyprus', 'Sudan', 'Guadaloupe', 'Haiti', 'Gibraltar', 'Cambodia', 'Congo', 'Kuwait',
     'Kyrgyz Republic', "Cote D'Ivoire", 'Bahamas', 'North Korea', 'United Arab Emirates', 'Gambia', 'Oman', 'Benin',
     'Rwanda', 'Sao Tome and Principe', 'Algeria', 'US Virgin Islands', 'Niger', 'Macao', 'Kiribati', 'Dominica',
     'Timor-Leste', 'Monaco', 'Panama', 'Martinique', "Lao People's Democratic Republic", 'Cameroon', 'Turkmenistan',
     'Uganda', 'Burkina Faso', 'Mali', 'Bahrain', 'British Virgin Islands', 'Brunei Darussalam', 'Holy See',
     'Swaziland', 'Maldives', 'Malta', 'Tanzania', 'Guam', 'Madagascar', 'Jordan', 'Saudi Arabia', 'French Guiana',
     'Guyana', 'Yemen', 'Gabon', 'Equatorial Guinea', 'Papua New Guinea', 'Cayman Islands', 'Cape Verde', 'Lesotho',
     'St. Kitts and Nevis', 'Togo', 'Botswana', 'St. Lucia', 'Bhutan', 'Serbia and Montenegro', 'Afghanistan',
     'Guinea-Bissau', 'Comoros', 'Suriname', 'Faeroe Islands', 'Marshall Islands', 'Sierra Leone', 'Anguilla', 'Samoa',
     'Liberia', 'British Indian Ocean Territory', 'Bermuda', 'Turks and Caicos Islands', 'Somalia', 'Andorra',
     'Mayotte', 'Solomon Islands', 'Vanuatu', 'Seychelles', 'Aruba', 'Fiji', 'Tonga', 'St. Helena', 'Mauritania',
     'Tokelau', 'Chad', 'Northern Mariana Islands']